name: file_testing
version: 2.2.0
authors:
- Todd Volkert <tvolkert@google.com>
description: Testing utilities for package:file
homepage: https://github.com/google/file.dart/packages/file_testing

dependencies:
  meta: ^1.1.2
  test: ^1.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'
