name: Dart

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  correctness:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [file, file_testing]

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: dev

      - name: Install ${{ matrix.package }} dependencies
        working-directory: packages/${{ matrix.package }}
        run: dart pub get

      - name: Verify formatting in ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze package ${{ matrix.package }} source
        working-directory: packages/${{ matrix.package }}
        run: dart analyze --fatal-infos

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        package: [file]
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev]

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install ${{ matrix.package }} dependencies
        working-directory: packages/${{ matrix.package }}
        run: dart pub get

      - name: Run ${{ matrix.package }} Tests
        working-directory: packages/${{ matrix.package }}
        run: dart pub run test -j1
